"""Add user fields

Revision ID: 9672262c1f55
Revises: 39379a0e214b
Create Date: 2025-12-11 17:58:35.132844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9672262c1f55'
down_revision: Union[str, Sequence[str], None] = '39379a0e214b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('drill_sessions')
    op.add_column('users', sa.Column('username', sa.String(), nullable=True))
    op.add_column('users', sa.Column('streak_days', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('exam_date', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_column('users', 'exam_date')
    op.drop_column('users', 'streak_days')
    op.drop_column('users', 'username')
    op.create_table('drill_sessions',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('difficulty', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('exam_date', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('passage_title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('passage_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('questions_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('original_score', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('final_mastery', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('traps_identified', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('drill_sessions_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('drill_sessions_pkey'))
    )
    # ### end Alembic commands ###
